version: '3.4'

networks:
  smstake:   
    ipam:
      config:
        - subnet: 10.0.10.0/24
 

services:

    db:
        image: mysql:5.7
        networks:
          - smstake
        ports:
          - "3306"
        env_file:
          - configuration.env
        environment:
          MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
          MYSQL_DATABASE: ${DB_NAME}
          MYSQL_USER: ${DB_USER}
          MYSQL_PASSWORD: ${DB_PASSWORD}
        volumes:
          - mysql_data:/var/lib/mysql
        deploy:
          mode: replicated
          replicas: 1
          
    app:
        image: SMSTAKE_VERSION
        ports:
          - 8000:80
        networks:
          - smstake
        depends_on:
          - db
        deploy:
          mode: replicated
          replicas: 2

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        networks:
          - smstake
        depends_on:
          - db
        environment:
          PMA_HOST: db
          PMA_PORT: 3306
          MYSQL_USER: tara
          MYSQL_PASSWORD: password
        ports:
          - '8082:80'
        deploy:
          mode: replicated
          replicas: 1

volumes:
    mysql_data:

